const ALIASES=[[/^google\./i,['go','google']],[/(^|\.)gmail\.com$/i,['gm','gmail']],[/(^|\.)youtube\.com$/i,['yt','youtube']],[/(^|\.)instagram\.com$/i,['ig','insta','instagram']],[/(^|\.)github\.com$/i,['gh','github']],[/(^|\.)twitch\.tv$/i,['tw','twitch']]];
const norm=(v)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const compact=(v)=>norm(v).replace(/[^a-z0-9]+/g,'');
const site=(u)=>{try{return new URL(u).hostname.replace(/^www\./,'');}catch{return String(u||'');}};
export function looksLikeAddress(value){return /^(?:[a-z][a-z0-9+.-]*:\/\/|localhost(?::\d+)?(?:\/|$)|[^\s]+\.[a-z]{2,}(?:[/:?#]|$))/i.test(String(value||'').trim());}
function score(q,title,url){const n=norm(q),c=compact(q);let host=site(url),hn=norm(host),hc=compact(host),tn=norm(title),tc=compact(title),un=norm(url),s=0;if(hn===n||hc===c)s=Math.max(s,320);if(hn.startsWith(n))s=Math.max(s,290);if(hc.startsWith(c))s=Math.max(s,280);if(tn.startsWith(n))s=Math.max(s,260);if(tc.startsWith(c))s=Math.max(s,250);if(hn.split('.').some((p)=>p.startsWith(n)))s=Math.max(s,240);if(ALIASES.some(([r,a])=>r.test(host)&&a.some((x)=>x===n||x.startsWith(n))))s=Math.max(s,300);if(tn.includes(n))s=Math.max(s,175);if(un.includes(n))s=Math.max(s,145);return s;}
export function buildOmniboxSuggestions(query,history=[],bookmarks=[],tabs=[],privateMode=false,now=Date.now()){
  const raw=String(query||'').trim(); if(!raw)return[]; const merged=new Map();
  const add=(url,title,extra={})=>{if(!/^https?:/i.test(url))return;const x=merged.get(url)||{url,title:title||url,at:0,visits:0,bookmark:false,tab:false,history:false};x.title=title||x.title;x.at=Math.max(x.at,Number(extra.at||0));x.visits=Math.max(x.visits,Number(extra.visits||0));x.bookmark||=!!extra.bookmark;x.tab||=!!extra.tab;x.history||=!!extra.history;merged.set(url,x);};
  bookmarks.forEach((x)=>add(x.url,x.title,{bookmark:true})); tabs.forEach((x)=>{if(!x.internalPage && !!x.private===!!privateMode)add(x.url,x.title,{tab:true,at:x.lastActiveAt});}); if(!privateMode)history.forEach((x)=>add(x.url,x.title,{history:true,at:x.at,visits:x.visits||1}));
  const out=[]; for(const x of merged.values()){let s=score(raw,x.title,x.url);if(!s)continue;if(x.bookmark)s+=40;if(x.tab)s+=34;if(x.history)s+=Math.min(38,Math.log2(Math.max(1,x.visits)+1)*9);if(x.at){const age=Math.max(0,(now-x.at)/3600000);s+=Math.max(0,34-Math.log2(age+1)*5);}const source=x.tab?'tab':x.bookmark?'bookmark':'history';out.push({id:`${source}:${x.url}`,url:x.url,title:x.title||site(x.url),subtitle:source==='tab'?`Aba aberta · ${site(x.url)}`:source==='bookmark'?`Favorito · ${site(x.url)}`:`${x.visits||1} visita${(x.visits||1)===1?'':'s'} · ${site(x.url)}`,source,score:s});}
  out.sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title,'pt-BR'));const result=out.slice(0,7);if(looksLikeAddress(raw)){const u=/^[a-z][a-z0-9+.-]*:\/\//i.test(raw)?raw:`https://${raw}`;if(!result.some((x)=>x.url===u))result.unshift({id:`url:${u}`,url:u,title:`Ir para ${raw}`,subtitle:'Endereço digitado',source:'url',score:999});}else result.push({id:`search:${raw}`,url:raw,title:`Pesquisar “${raw}”`,subtitle:'Usar mecanismo de pesquisa padrão',source:'search',score:1});return result.slice(0,8);
}
